version 0.6

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,8 +1,25 @@
-AC_INIT(igraph, 0.5.5, csardi@rmki.kfki.hu)
+AC_INIT(igraph, 0.6, csardi.gabor@gmail.com)
 AC_CONFIG_SRCDIR(src/rinterface.c)
 AC_CONFIG_HEADERS(src/config.h)
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+   echo "could not determine R_HOME"
+   exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CXX=`"${R_HOME}/bin/R" CMD config CXX`
+FC=`"${R_HOME}/bin/R" CMD config FC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXXFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+FCFLAGS=`"${R_HOME}/bin/R" CMD config FCFLAGS`
+FLIBS=`"${R_HOME}/bin/R" CMD config FLIBS`
+
+AC_LANG(C)
 AC_PROG_CC
+
+AC_PROG_FC
 
 # Tricky check for C++ compiler, because Autoconf has a weird bug:
 # http://lists.gnu.org/archive/html/autoconf/2006-03/msg00067.html
@@ -17,27 +34,10 @@ const char hw[] = "Hello, World\n";]],
         [AC_MSG_ERROR([no C++ compiler found or it cannot create executables])])
 AC_LANG_POP([C++])
 
-AC_CHECK_FUNCS(fmemopen, [HAVE_FMEMOPEN=1], [HAVE_FMEMOPEN=0])
-AC_SUBST(HAVE_FMEMOPEN)
-
-AC_CHECK_FUNCS(open_memstream, [HAVE_OPEN_MEMSTREAM=1], [HAVE_OPEN_MEMSTREAM=0])
-AC_SUBST(HAVE_OPEN_MEMSTREAM)
-
 LIBS_SAVE=$LIBS
 LIBS="$LIBS -lm"
-AC_CHECK_FUNCS([rintf], [HAVE_RINTF=1], [HAVE_RINTF=0])
-AC_CHECK_FUNCS([finite], [HAVE_FINITE=1], [HAVE_FINITE=0])
-AC_CHECK_FUNCS([expm1], [HAVE_EXPM1=1], [HAVE_EMPM1=0])
-AC_CHECK_FUNCS([rint], [HAVE_RINT=1], [HAVE_RINT=0])
-AC_CHECK_FUNCS([log2], [HAVE_LOG2=1], [HAVE_LOG2=0])
-AC_CHECK_FUNCS([logbl], [HAVE_LOGBL=1], [HAVE_LOGBL=0])
-AC_CHECK_FUNCS([snprintf], [HAVE_SNPRINTF=1], [HAVE_SNPRINTF=0])
-AC_CHECK_FUNCS([log1p], [HAVE_LOG1P=1], [HAVE_LOG1P=0])
-AC_CHECK_FUNCS([round], [HAVE_ROUND=1], [HAVE_ROUND=0])
-AC_CHECK_FUNCS([fmin], [HAVE_FMIN=1], [HAVE_FMIN=0])
+AC_CHECK_FUNCS([rintf finite expm1 rint log2 logbl snprintf log1p round fmin])
 LIBS=$LIBS_SAVE
-AC_SUBST(HAVE_RINTF)
-AC_SUBST(HAVE_FINITE)
 
 AC_CHECK_HEADER([sys/times.h], 
       [AC_DEFINE([HAVE_TIMES_H], [1], [Define to 1 if you have the sys/times.h header])])
@@ -79,6 +79,7 @@ if test $graphml_support = yes; then
 fi
 AC_SUBST(HAVE_LIBXML)
 
+AC_LANG_PUSH([C++])
 HAVE_GMP=0
 GMP_LIBS=""
 gmp_support=no
@@ -95,7 +96,17 @@ if test "x$enable_gmp" != "xno"; then
 fi
 AC_SUBST(HAVE_GMP)
 AC_SUBST(GMP_LIBS)
+AC_LANG_POP([C++])
 
-AC_CONFIG_FILES([R/config.R src/Makevars])
+glpk_support=yes
+AC_DEFINE([HAVE_GLPK], [1], [Define to 1 if you have the GLPK library])
+HAVE_GLPK=1
+GLPK_LIBS=""
+AC_SUBST(HAVE_GLPK)
+AC_SUBST(GLPK_LIBS)
+
+AC_DEFINE(IGRAPH_THREAD_LOCAL, [], [We don't care about thread-local storage in R])
+
+AC_CONFIG_FILES([src/Makevars])
 
 AC_OUTPUT
